### ISSUE TITLE
Allow functionality for aces to be used as 11 or 1...

### ISSUE THREAD

**Issue by lucas98774** [lucas98774/rl-blackjack#6]
Aces can be high or low in blackjack. Look for a way to allow them to be used as either --- maybe start every ace as 11 and then if a bust occurs then change it to 1? Is there a better way to do this ...

**Comment by lucas98774** [comment]
Check out the update for this. I think the workaround is a bit more intuitive. There shouldn't ever be a reason to change an ace's value back from 1 to 11 again correct? Closing this issue for now since the functionality is provided ... We can keep this in mind and discuss this as an area for improvement but open a new issue if we want to redesign this since that is a separate task.

**Comment by Ndiedrick21** [comment]
I do have one concern with how this is implented. If the cards are to be used again for another round, then the value for the ace will have to be reset between rounds. This could impact total calculations for future rounds. I do not think this would be a probelm if a new deck is created for every round, but that would use unnecessary memory.

**Comment by lucas98774** [comment]
Nathan you are right. Currently the workaround for this is that a deck is reset after each round but to make this more accurate we could change this. I do think we should come up with a better solution before making this change. Keep with the current implementation (for argument's sake) the only aces that get changed are the ones in a player's hand which will not be redealt until the deck is reset (and initialized to 11). Also currently "reshuffling a deck" is simply creating a new deck (all the aces will be 11). Any additional thoughts on problems this could create? Any better ways of structuring this or any other ideas?
